# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

    lane :before_integration do
        reset_git_repo(force: true)
        ensure_git_status_clean
        git_pull
        increment_build_number({
            build_number: latest_testflight_build_number(
            initial_build_number: 0,
            username: 'romain.sickenberg@liip.ch',
            app_identifier: 'me.romainsickenberg.fortnite-wiki'
            ) + 1,
        })
        cocoapods(repo_update: true)
    end

    lane :after_integration do
        upload_to_testflight(skip_waiting_for_build_processing: true)
    end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    ensure_git_status_clean
    prompt(
        text: "Did you updated the version on root settings ?",
	    boolean: true
    )
    prompt(
        text: "Did you set JSON to prod ?",
        boolean: true
)
    increment_build_number
    cocoapods(
        clean: true,
        podfile: "Podfile",
        try_repo_update_on_error: true
    )
    build_app(scheme: "fort_to_nite")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

  desc "Release a build to AppStore"
  lane :release do
  ensure_git_status_clean
  get_certificates           # invokes cert
  get_provisioning_profile   # invokes sigh
    prompt(
        text: "Did you updated the version on root settings ?",
        boolean: true
    )
    prompt(
        text: "Did you set JSON to prod ?",
        boolean: true
    )
    increment_build_number
    cocoapods(
        clean: true,
        podfile: "Podfile",
        try_repo_update_on_error: true
    )
    build_app(scheme: "fort_to_nite", include_bitcode: true)
    deliver(
        submit_for_review: true,
        force: true,
        metadata_path: "./metadata",
        skip_screenshots: true,
    )
  end

  desc "Frame some screenshots"
  lane :frame do
    frameit(path: './screenshots/en-US/')
  end
end

platform :mac do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    ensure_git_status_clean
    prompt(
        text: "Did you updated the version on root settings ?",
        boolean: true
    )
    prompt(
        text: "Did you set JSON to prod ?",
        boolean: true
    )
    increment_build_number
    cocoapods(
        clean: true,
        podfile: "Podfile",
        try_repo_update_on_error: true
    )
    build_app(scheme: "fort_to_nite-catalyst")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
